/**
 * Los 184 idiomas con código ISO 639-1, con su ISO 639-3, su nombre en español,
 * en inglés y en el propio idioma. Los nombres salen de CLDR (Intl.DisplayNames)
 * y los códigos del dataset ISO 639-2 de la Library of Congress; la columna de
 * locales BCP 47 está curada a mano, solo donde la variante regional importa.
 *
 * Generado una vez y versionado a propósito: es una tabla estable y no merece
 * una dependencia en tiempo de ejecución.
 */

export interface Language {
  readonly iso1: string;
  readonly iso3: string;
  readonly en: string;
  readonly es: string;
  readonly native: string;
  readonly locales?: readonly string[];
}

export const LANGUAGES: readonly Language[] = [
  { iso1: 'ab', iso3: 'abk', en: 'Abkhazian', es: 'Abjasio', native: 'Аҧсуа', },
  { iso1: 'aa', iso3: 'aar', en: 'Afar', es: 'Afar', native: 'Afaraf', },
  { iso1: 'af', iso3: 'afr', en: 'Afrikaans', es: 'Afrikáans', native: 'Afrikaans', },
  { iso1: 'ak', iso3: 'aka', en: 'Akan', es: 'Akan', native: 'Akan', },
  { iso1: 'sq', iso3: 'sqi', en: 'Albanian', es: 'Albanés', native: 'Shqip', },
  { iso1: 'am', iso3: 'amh', en: 'Amharic', es: 'Amárico', native: 'አማርኛ', },
  { iso1: 'ar', iso3: 'ara', en: 'Arabic', es: 'Árabe', native: 'العربية', locales: ['ar-SA', 'ar-EG', 'ar-MA', 'ar-AE'], },
  { iso1: 'an', iso3: 'arg', en: 'Aragonese', es: 'Aragonés', native: 'Aragonés', },
  { iso1: 'hy', iso3: 'hye', en: 'Armenian', es: 'Armenio', native: 'Հայերեն', },
  { iso1: 'as', iso3: 'asm', en: 'Assamese', es: 'Asamés', native: 'অসমীয়া', },
  { iso1: 'av', iso3: 'ava', en: 'Avaric', es: 'Avar', native: 'Авар', },
  { iso1: 'ae', iso3: 'ave', en: 'Avestan', es: 'Avéstico', native: 'avesta', },
  { iso1: 'ay', iso3: 'aym', en: 'Aymara', es: 'Aimara', native: 'Aymar', },
  { iso1: 'az', iso3: 'aze', en: 'Azerbaijani', es: 'Azerbaiyano', native: 'Azərbaycanca', },
  { iso1: 'bm', iso3: 'bam', en: 'Bambara', es: 'Bambara', native: 'Bamanankan', },
  { iso1: 'bn', iso3: 'ben', en: 'Bangla', es: 'Bengalí', native: 'বাংলা', locales: ['bn-BD', 'bn-IN'], },
  { iso1: 'ba', iso3: 'bak', en: 'Bashkir', es: 'Baskir', native: 'Башҡортса', },
  { iso1: 'eu', iso3: 'eus', en: 'Basque', es: 'Euskera', native: 'Euskara', },
  { iso1: 'be', iso3: 'bel', en: 'Belarusian', es: 'Bielorruso', native: 'Беларуская', },
  { iso1: 'bh', iso3: 'bih', en: 'Bhojpuri', es: 'Bhoyapurí', native: 'भोजपुरी', },
  { iso1: 'bi', iso3: 'bis', en: 'Bislama', es: 'Bislama', native: 'Bislama', },
  { iso1: 'bs', iso3: 'bos', en: 'Bosnian', es: 'Bosnio', native: 'Bosanski', },
  { iso1: 'br', iso3: 'bre', en: 'Breton', es: 'Bretón', native: 'Brezhoneg', },
  { iso1: 'bg', iso3: 'bul', en: 'Bulgarian', es: 'Búlgaro', native: 'Български', },
  { iso1: 'my', iso3: 'mya', en: 'Burmese', es: 'Birmano', native: 'မြန်မာဘာသာ', },
  { iso1: 'ca', iso3: 'cat', en: 'Catalan', es: 'Catalán', native: 'Català', },
  { iso1: 'ch', iso3: 'cha', en: 'Chamorro', es: 'Chamorro', native: 'Chamoru', },
  { iso1: 'ce', iso3: 'che', en: 'Chechen', es: 'Checheno', native: 'Нохчийн', },
  { iso1: 'zh', iso3: 'zho', en: 'Chinese', es: 'Chino', native: '中文', locales: ['zh-Hans', 'zh-Hant', 'zh-CN', 'zh-TW', 'zh-HK'], },
  { iso1: 'cu', iso3: 'chu', en: 'Church Slavic', es: 'Eslavo eclesiástico', native: 'Словѣ́ньскъ', },
  { iso1: 'cv', iso3: 'chv', en: 'Chuvash', es: 'Chuvasio', native: 'Чӑвашла', },
  { iso1: 'kw', iso3: 'cor', en: 'Cornish', es: 'Córnico', native: 'Kernewek', },
  { iso1: 'co', iso3: 'cos', en: 'Corsican', es: 'Corso', native: 'Corsu', },
  { iso1: 'cr', iso3: 'cre', en: 'Cree', es: 'Cree', native: 'ᓀᐦᐃᔭᐍᐏᐣ', },
  { iso1: 'hr', iso3: 'hrv', en: 'Croatian', es: 'Croata', native: 'Hrvatski', },
  { iso1: 'cs', iso3: 'ces', en: 'Czech', es: 'Checo', native: 'Čeština', locales: ['cs-CZ'], },
  { iso1: 'da', iso3: 'dan', en: 'Danish', es: 'Danés', native: 'Dansk', locales: ['da-DK'], },
  { iso1: 'dv', iso3: 'div', en: 'Divehi', es: 'Divehi', native: 'Divehi', },
  { iso1: 'nl', iso3: 'nld', en: 'Dutch', es: 'Neerlandés', native: 'Nederlands', locales: ['nl-NL', 'nl-BE'], },
  { iso1: 'dz', iso3: 'dzo', en: 'Dzongkha', es: 'Dzongkha', native: 'རྫོང་ཁ', },
  { iso1: 'en', iso3: 'eng', en: 'English', es: 'Inglés', native: 'English', locales: ['en-US', 'en-GB', 'en-AU', 'en-CA', 'en-IN'], },
  { iso1: 'eo', iso3: 'epo', en: 'Esperanto', es: 'Esperanto', native: 'Esperanto', },
  { iso1: 'et', iso3: 'est', en: 'Estonian', es: 'Estonio', native: 'Eesti', },
  { iso1: 'ee', iso3: 'ewe', en: 'Ewe', es: 'Ewé', native: 'Eʋegbe', },
  { iso1: 'fo', iso3: 'fao', en: 'Faroese', es: 'Feroés', native: 'Føroyskt', },
  { iso1: 'fj', iso3: 'fij', en: 'Fijian', es: 'Fiyiano', native: 'Na Vosa Vaka-Viti', },
  { iso1: 'tl', iso3: 'tgl', en: 'Filipino', es: 'Filipino', native: 'Tagalog', },
  { iso1: 'fi', iso3: 'fin', en: 'Finnish', es: 'Finés', native: 'Suomi', locales: ['fi-FI'], },
  { iso1: 'fr', iso3: 'fra', en: 'French', es: 'Francés', native: 'Français', locales: ['fr-FR', 'fr-CA', 'fr-BE', 'fr-CH'], },
  { iso1: 'ff', iso3: 'ful', en: 'Fula', es: 'Fula', native: 'Fulfulde', },
  { iso1: 'gl', iso3: 'glg', en: 'Galician', es: 'Gallego', native: 'Galego', },
  { iso1: 'lg', iso3: 'lug', en: 'Ganda', es: 'Ganda', native: 'Luganda', },
  { iso1: 'ka', iso3: 'kat', en: 'Georgian', es: 'Georgiano', native: 'ქართული', },
  { iso1: 'de', iso3: 'deu', en: 'German', es: 'Alemán', native: 'Deutsch', locales: ['de-DE', 'de-AT', 'de-CH'], },
  { iso1: 'el', iso3: 'ell', en: 'Greek', es: 'Griego', native: 'Ελληνικά', locales: ['el-GR'], },
  { iso1: 'gn', iso3: 'grn', en: 'Guarani', es: 'Guaraní', native: 'Avañe\'ẽ', },
  { iso1: 'gu', iso3: 'guj', en: 'Gujarati', es: 'Guyaratí', native: 'ગુજરાતી', },
  { iso1: 'ht', iso3: 'hat', en: 'Haitian Creole', es: 'Criollo haitiano', native: 'Kreyòl Ayisyen', },
  { iso1: 'ha', iso3: 'hau', en: 'Hausa', es: 'Hausa', native: 'هَوُسَ', },
  { iso1: 'he', iso3: 'heb', en: 'Hebrew', es: 'Hebreo', native: 'עברית', locales: ['he-IL'], },
  { iso1: 'hz', iso3: 'her', en: 'Herero', es: 'Herero', native: 'Otjiherero', },
  { iso1: 'hi', iso3: 'hin', en: 'Hindi', es: 'Hindi', native: 'हिन्दी', locales: ['hi-IN'], },
  { iso1: 'ho', iso3: 'hmo', en: 'Hiri Motu', es: 'Hiri motu', native: 'Hiri Motu', },
  { iso1: 'hu', iso3: 'hun', en: 'Hungarian', es: 'Húngaro', native: 'Magyar', locales: ['hu-HU'], },
  { iso1: 'is', iso3: 'isl', en: 'Icelandic', es: 'Islandés', native: 'Íslenska', },
  { iso1: 'io', iso3: 'ido', en: 'Ido', es: 'Ido', native: 'Ido', },
  { iso1: 'ig', iso3: 'ibo', en: 'Igbo', es: 'Igbo', native: 'Igbo', },
  { iso1: 'id', iso3: 'ind', en: 'Indonesian', es: 'Indonesio', native: 'Bahasa Indonesia', locales: ['id-ID'], },
  { iso1: 'ia', iso3: 'ina', en: 'Interlingua', es: 'Interlingua', native: 'Interlingua', },
  { iso1: 'ie', iso3: 'ile', en: 'Interlingue', es: 'Interlingue', native: 'Interlingue', },
  { iso1: 'iu', iso3: 'iku', en: 'Inuktitut', es: 'Inuktitut', native: 'ᐃᓄᒃᑎᑐᑦ', },
  { iso1: 'ik', iso3: 'ipk', en: 'Inupiaq', es: 'Inupiaq', native: 'Iñupiak', },
  { iso1: 'ga', iso3: 'gle', en: 'Irish', es: 'Irlandés', native: 'Gaeilge', },
  { iso1: 'it', iso3: 'ita', en: 'Italian', es: 'Italiano', native: 'Italiano', locales: ['it-IT', 'it-CH'], },
  { iso1: 'ja', iso3: 'jpn', en: 'Japanese', es: 'Japonés', native: '日本語', locales: ['ja-JP'], },
  { iso1: 'jv', iso3: 'jav', en: 'Javanese', es: 'Javanés', native: 'Basa Jawa', },
  { iso1: 'kl', iso3: 'kal', en: 'Kalaallisut', es: 'Groenlandés', native: 'Kalaallisut', },
  { iso1: 'kn', iso3: 'kan', en: 'Kannada', es: 'Canarés', native: 'ಕನ್ನಡ', },
  { iso1: 'kr', iso3: 'kau', en: 'Kanuri', es: 'Kanuri', native: 'Kanuri', },
  { iso1: 'ks', iso3: 'kas', en: 'Kashmiri', es: 'Cachemir', native: 'كشميري', },
  { iso1: 'kk', iso3: 'kaz', en: 'Kazakh', es: 'Kazajo', native: 'Қазақша', },
  { iso1: 'km', iso3: 'khm', en: 'Khmer', es: 'Jemer', native: 'ភាសាខ្មែរ', },
  { iso1: 'ki', iso3: 'kik', en: 'Kikuyu', es: 'Kikuyu', native: 'Gĩkũyũ', },
  { iso1: 'rw', iso3: 'kin', en: 'Kinyarwanda', es: 'Kinyarwanda', native: 'Kinyarwanda', },
  { iso1: 'kv', iso3: 'kom', en: 'Komi', es: 'Komi', native: 'Коми', },
  { iso1: 'kg', iso3: 'kon', en: 'Kongo', es: 'Kongo', native: 'Kongo', },
  { iso1: 'ko', iso3: 'kor', en: 'Korean', es: 'Coreano', native: '한국어', locales: ['ko-KR'], },
  { iso1: 'kj', iso3: 'kua', en: 'Kuanyama', es: 'Kuanyama', native: 'Kuanyama', },
  { iso1: 'ku', iso3: 'kur', en: 'Kurdish', es: 'Kurdo', native: 'Kurdî', },
  { iso1: 'ky', iso3: 'kir', en: 'Kyrgyz', es: 'Kirguís', native: 'Кыргызча', },
  { iso1: 'lo', iso3: 'lao', en: 'Lao', es: 'Lao', native: 'ພາສາລາວ', },
  { iso1: 'la', iso3: 'lat', en: 'Latin', es: 'Latín', native: 'Latina', },
  { iso1: 'lv', iso3: 'lav', en: 'Latvian', es: 'Letón', native: 'Latviešu', },
  { iso1: 'li', iso3: 'lim', en: 'Limburgish', es: 'Limburgués', native: 'Limburgs', },
  { iso1: 'ln', iso3: 'lin', en: 'Lingala', es: 'Lingala', native: 'Lingála', },
  { iso1: 'lt', iso3: 'lit', en: 'Lithuanian', es: 'Lituano', native: 'Lietuvių', },
  { iso1: 'lu', iso3: 'lub', en: 'Luba-Katanga', es: 'Luba-katanga', native: 'Tshiluba', },
  { iso1: 'lb', iso3: 'ltz', en: 'Luxembourgish', es: 'Luxemburgués', native: 'Lëtzebuergesch', },
  { iso1: 'mk', iso3: 'mkd', en: 'Macedonian', es: 'Macedonio', native: 'Македонски', },
  { iso1: 'mg', iso3: 'mlg', en: 'Malagasy', es: 'Malgache', native: 'Malagasy', },
  { iso1: 'ms', iso3: 'msa', en: 'Malay', es: 'Malayo', native: 'Bahasa Melayu', locales: ['ms-MY'], },
  { iso1: 'ml', iso3: 'mal', en: 'Malayalam', es: 'Malayálam', native: 'മലയാളം', },
  { iso1: 'mt', iso3: 'mlt', en: 'Maltese', es: 'Maltés', native: 'Malti', },
  { iso1: 'gv', iso3: 'glv', en: 'Manx', es: 'Manés', native: 'Gaelg', },
  { iso1: 'mi', iso3: 'mri', en: 'Māori', es: 'Maorí', native: 'Māori', },
  { iso1: 'mr', iso3: 'mar', en: 'Marathi', es: 'Maratí', native: 'मराठी', },
  { iso1: 'mh', iso3: 'mah', en: 'Marshallese', es: 'Marshalés', native: 'Kajin M̧ajeļ', },
  { iso1: 'mn', iso3: 'mon', en: 'Mongolian', es: 'Mongol', native: 'Монгол', },
  { iso1: 'na', iso3: 'nau', en: 'Nauru', es: 'Nauruano', native: 'Dorerin Naoero', },
  { iso1: 'nv', iso3: 'nav', en: 'Navajo', es: 'Navajo', native: 'Diné Bizaad', },
  { iso1: 'ng', iso3: 'ndo', en: 'Ndonga', es: 'Ndonga', native: 'Owambo', },
  { iso1: 'ne', iso3: 'nep', en: 'Nepali', es: 'Nepalí', native: 'नेपाली', },
  { iso1: 'nd', iso3: 'nde', en: 'North Ndebele', es: 'Ndebele septentrional', native: 'isiNdebele', },
  { iso1: 'se', iso3: 'sme', en: 'Northern Sami', es: 'Sami septentrional', native: 'Sámegiella', },
  { iso1: 'no', iso3: 'nor', en: 'Norwegian', es: 'Noruego', native: 'Norsk', locales: ['nb-NO', 'nn-NO'], },
  { iso1: 'nb', iso3: 'nob', en: 'Norwegian Bokmål', es: 'Noruego bokmal', native: 'Norsk (Bokmål)', },
  { iso1: 'nn', iso3: 'nno', en: 'Norwegian Nynorsk', es: 'Noruego nynorsk', native: 'Norsk (Nynorsk)', },
  { iso1: 'ny', iso3: 'nya', en: 'Nyanja', es: 'Nyanja', native: 'Chichewa', },
  { iso1: 'oc', iso3: 'oci', en: 'Occitan', es: 'Occitano', native: 'Occitan', },
  { iso1: 'or', iso3: 'ori', en: 'Odia', es: 'Oriya', native: 'ଓଡି଼ଆ', },
  { iso1: 'oj', iso3: 'oji', en: 'Ojibwa', es: 'Ojibwa', native: 'ᐊᓂᔑᓈᐯᒧᐎᓐ', },
  { iso1: 'om', iso3: 'orm', en: 'Oromo', es: 'Oromo', native: 'Afaan Oromoo', },
  { iso1: 'os', iso3: 'oss', en: 'Ossetic', es: 'Osético', native: 'Ирон æвзаг', },
  { iso1: 'pi', iso3: 'pli', en: 'Pali', es: 'Pali', native: 'पाऴि', },
  { iso1: 'ps', iso3: 'pus', en: 'Pashto', es: 'Pastún', native: 'پښتو', },
  { iso1: 'fa', iso3: 'fas', en: 'Persian', es: 'Persa', native: 'فارسی', locales: ['fa-IR', 'fa-AF'], },
  { iso1: 'pl', iso3: 'pol', en: 'Polish', es: 'Polaco', native: 'Polski', locales: ['pl-PL'], },
  { iso1: 'pt', iso3: 'por', en: 'Portuguese', es: 'Portugués', native: 'Português', locales: ['pt-BR', 'pt-PT'], },
  { iso1: 'pa', iso3: 'pan', en: 'Punjabi', es: 'Punyabí', native: 'ਪੰਜਾਬੀ', },
  { iso1: 'qu', iso3: 'que', en: 'Quechua', es: 'Quechua', native: 'Runa Simi', },
  { iso1: 'ro', iso3: 'ron', en: 'Romanian', es: 'Rumano', native: 'Română', locales: ['ro-RO', 'ro-MD'], },
  { iso1: 'rm', iso3: 'roh', en: 'Romansh', es: 'Romanche', native: 'Rumantsch', },
  { iso1: 'rn', iso3: 'run', en: 'Rundi', es: 'Kirundi', native: 'Kirundi', },
  { iso1: 'ru', iso3: 'rus', en: 'Russian', es: 'Ruso', native: 'Русский', locales: ['ru-RU'], },
  { iso1: 'sm', iso3: 'smo', en: 'Samoan', es: 'Samoano', native: 'Gagana Sāmoa', },
  { iso1: 'sg', iso3: 'sag', en: 'Sango', es: 'Sango', native: 'Sängö', },
  { iso1: 'sa', iso3: 'san', en: 'Sanskrit', es: 'Sánscrito', native: 'संस्कृतम्', },
  { iso1: 'sc', iso3: 'srd', en: 'Sardinian', es: 'Sardo', native: 'Sardu', },
  { iso1: 'gd', iso3: 'gla', en: 'Scottish Gaelic', es: 'Gaélico escocés', native: 'Gàidhlig', },
  { iso1: 'sr', iso3: 'srp', en: 'Serbian', es: 'Serbio', native: 'Српски', locales: ['sr-Cyrl', 'sr-Latn'], },
  { iso1: 'sn', iso3: 'sna', en: 'Shona', es: 'Shona', native: 'ChiShona', },
  { iso1: 'ii', iso3: 'iii', en: 'Sichuan Yi', es: 'Yi de Sichuán', native: 'ꆈꌠ꒿ Nuosuhxop', },
  { iso1: 'sd', iso3: 'snd', en: 'Sindhi', es: 'Sindi', native: 'سنڌي‎', },
  { iso1: 'si', iso3: 'sin', en: 'Sinhala', es: 'Cingalés', native: 'සිංහල', },
  { iso1: 'sk', iso3: 'slk', en: 'Slovak', es: 'Eslovaco', native: 'Slovenčina', },
  { iso1: 'sl', iso3: 'slv', en: 'Slovenian', es: 'Esloveno', native: 'Slovenščina', },
  { iso1: 'so', iso3: 'som', en: 'Somali', es: 'Somalí', native: 'Soomaaliga', },
  { iso1: 'nr', iso3: 'nbl', en: 'South Ndebele', es: 'Ndebele meridional', native: 'isiNdebele', },
  { iso1: 'st', iso3: 'sot', en: 'Southern Sotho', es: 'Sotho meridional', native: 'Sesotho', },
  { iso1: 'es', iso3: 'spa', en: 'Spanish', es: 'Español', native: 'Español', locales: ['es-ES', 'es-MX', 'es-AR', 'es-CO', 'es-CL', 'es-US'], },
  { iso1: 'su', iso3: 'sun', en: 'Sundanese', es: 'Sundanés', native: 'Basa Sunda', },
  { iso1: 'sw', iso3: 'swa', en: 'Swahili', es: 'Suajili', native: 'Kiswahili', locales: ['sw-KE', 'sw-TZ'], },
  { iso1: 'ss', iso3: 'ssw', en: 'Swati', es: 'Suazi', native: 'SiSwati', },
  { iso1: 'sv', iso3: 'swe', en: 'Swedish', es: 'Sueco', native: 'Svenska', locales: ['sv-SE', 'sv-FI'], },
  { iso1: 'ty', iso3: 'tah', en: 'Tahitian', es: 'Tahitiano', native: 'Reo Mā’ohi', },
  { iso1: 'tg', iso3: 'tgk', en: 'Tajik', es: 'Tayiko', native: 'Тоҷикӣ', },
  { iso1: 'ta', iso3: 'tam', en: 'Tamil', es: 'Tamil', native: 'தமிழ்', locales: ['ta-IN', 'ta-LK'], },
  { iso1: 'tt', iso3: 'tat', en: 'Tatar', es: 'Tártaro', native: 'Татарча', },
  { iso1: 'te', iso3: 'tel', en: 'Telugu', es: 'Telugu', native: 'తెలుగు', },
  { iso1: 'th', iso3: 'tha', en: 'Thai', es: 'Tailandés', native: 'ภาษาไทย', locales: ['th-TH'], },
  { iso1: 'bo', iso3: 'bod', en: 'Tibetan', es: 'Tibetano', native: 'བོད་ཡིག', },
  { iso1: 'ti', iso3: 'tir', en: 'Tigrinya', es: 'Tigriña', native: 'ትግርኛ', },
  { iso1: 'to', iso3: 'ton', en: 'Tongan', es: 'Tongano', native: 'faka Tonga', },
  { iso1: 'ts', iso3: 'tso', en: 'Tsonga', es: 'Tsonga', native: 'Xitsonga', },
  { iso1: 'tn', iso3: 'tsn', en: 'Tswana', es: 'Setsuana', native: 'Setswana', },
  { iso1: 'tr', iso3: 'tur', en: 'Turkish', es: 'Turco', native: 'Türkçe', locales: ['tr-TR'], },
  { iso1: 'tk', iso3: 'tuk', en: 'Turkmen', es: 'Turcomano', native: 'Türkmençe', },
  { iso1: 'tw', iso3: 'twi', en: 'Twi', es: 'Twi', native: 'Twi', },
  { iso1: 'uk', iso3: 'ukr', en: 'Ukrainian', es: 'Ucraniano', native: 'Українська', locales: ['uk-UA'], },
  { iso1: 'ur', iso3: 'urd', en: 'Urdu', es: 'Urdu', native: 'اردو', locales: ['ur-PK', 'ur-IN'], },
  { iso1: 'ug', iso3: 'uig', en: 'Uyghur', es: 'Uigur', native: 'ئۇيغۇرچه', },
  { iso1: 'uz', iso3: 'uzb', en: 'Uzbek', es: 'Uzbeko', native: 'O‘zbek', },
  { iso1: 've', iso3: 'ven', en: 'Venda', es: 'Venda', native: 'Tshivenḓa', },
  { iso1: 'vi', iso3: 'vie', en: 'Vietnamese', es: 'Vietnamita', native: 'Tiếng Việt', locales: ['vi-VN'], },
  { iso1: 'vo', iso3: 'vol', en: 'Volapük', es: 'Volapük', native: 'Volapük', },
  { iso1: 'wa', iso3: 'wln', en: 'Walloon', es: 'Valón', native: 'Walon', },
  { iso1: 'cy', iso3: 'cym', en: 'Welsh', es: 'Galés', native: 'Cymraeg', },
  { iso1: 'fy', iso3: 'fry', en: 'Western Frisian', es: 'Frisón occidental', native: 'Frysk', },
  { iso1: 'wo', iso3: 'wol', en: 'Wolof', es: 'Wólof', native: 'Wolof', },
  { iso1: 'xh', iso3: 'xho', en: 'Xhosa', es: 'Xhosa', native: 'isiXhosa', },
  { iso1: 'yi', iso3: 'yid', en: 'Yiddish', es: 'Yidis', native: 'ייִדיש', },
  { iso1: 'yo', iso3: 'yor', en: 'Yoruba', es: 'Yoruba', native: 'Yorùbá', },
  { iso1: 'za', iso3: 'zha', en: 'Zhuang', es: 'Zhuang', native: 'Cuengh', },
  { iso1: 'zu', iso3: 'zul', en: 'Zulu', es: 'Zulú', native: 'isiZulu', },
];
